name: gg
channels:
  - pytorch
  - plotly
  - defaults
dependencies:
  - pillow
  - pip
  - python=3.8
  - pytorch>=1.10.1
  - cudatoolkit=10.2
  - scipy
  - torchvision
  - pip:
    - moviepy
    - numpy
    - opencv-python
    - pandas
    - plotly
    - tensorboard>=1.15
    - tqdm
    - wget
    - lmdb
    - ray
    - ninja
    - scikit-learn
    - termcolor
